changeLogFile: ./changelog.xml
url: jdbc:postgresql://DevPilotAi-DB:5432/DevPilotAI
username: postgres
password: 5UP3R53R3T!
liquibase.hub.mode=off
classpath: ./lib/liquibase/internal/lib/postgresql.jar
